# ============================================
# Pipeline CI/CD pour Bank Account Application
# ============================================
# Ce pipeline automatise : build, test, qualité, package et déploiement Docker

# Définition des variables globales
variables:
  # Configuration Maven
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

  # Configuration Docker
  DOCKER_IMAGE_NAME: "$CI_REGISTRY_IMAGE/bank-account-app"
  DOCKER_TAG: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"

  # Configuration Java
  JAVA_VERSION: "17"

# Cache Maven pour accélérer les builds
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository/
    - backend/domain/target/
    - backend/application/target/
    - backend/infrastructure/target/
    - backend/boot/target/

# Définition des stages (étapes du pipeline)
stages:
  - build          # Compilation du projet
  - test           # Tests unitaires et d'intégration
  - quality        # Analyse de qualité et couverture
  - package        # Création de l'artefact JAR
  - docker-build   # Construction de l'image Docker
  - deploy         # Déploiement

# ============================================
# STAGE 1 : BUILD
# ============================================
# Compile le projet Maven multi-modules

build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "🔨 Compilation du projet..."
    - cd backend
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - backend/*/target/
    expire_in: 1 hour
  only:
    - branches
    - merge_requests
  tags:
    - docker

# ============================================
# STAGE 2 : TEST
# ============================================
# Exécute les tests unitaires

test:unit:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "🧪 Exécution des tests unitaires..."
    - cd backend
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - backend/*/target/surefire-reports/TEST-*.xml
    paths:
      - backend/*/target/surefire-reports/
      - backend/*/target/site/jacoco/
    expire_in: 1 week
  coverage: '/Total.*?([0-9]{1,3})%/'
  only:
    - branches
    - merge_requests
  tags:
    - docker

# Exécute les tests d'intégration
test:integration:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  services:
    - postgres:15-alpine
  variables:
    POSTGRES_DB: bankaccount_test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/bankaccount_test"
    SPRING_DATASOURCE_USERNAME: test
    SPRING_DATASOURCE_PASSWORD: test
  script:
    - echo "🧪 Exécution des tests d'intégration..."
    - cd backend
    - mvn $MAVEN_CLI_OPTS verify -DskipUnitTests
  artifacts:
    when: always
    reports:
      junit:
        - backend/*/target/failsafe-reports/TEST-*.xml
    paths:
      - backend/*/target/failsafe-reports/
    expire_in: 1 week
  only:
    - branches
    - merge_requests
  tags:
    - docker

# ============================================
# STAGE 3 : QUALITY
# ============================================
# Analyse la qualité du code avec JaCoCo

quality:coverage:
  stage: quality
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "📊 Analyse de la couverture de code..."
    - cd backend
    - mvn $MAVEN_CLI_OPTS jacoco:report jacoco:report-aggregate
    - echo "📈 Résumé de la couverture :"
    - cat boot/target/site/jacoco-aggregate/index.html | grep -o 'Total[^%]*%' || true
  artifacts:
    paths:
      - backend/boot/target/site/jacoco-aggregate/
    expire_in: 1 week
  coverage: '/Total.*?([0-9]{1,3})%/'
  only:
    - branches
    - merge_requests
  tags:
    - docker

# Vérification du style de code (optionnel)
quality:checkstyle:
  stage: quality
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "✨ Vérification du style de code..."
    - cd backend
    - mvn $MAVEN_CLI_OPTS checkstyle:check || true
  allow_failure: true
  only:
    - branches
    - merge_requests
  tags:
    - docker

# ============================================
# STAGE 4 : PACKAGE
# ============================================
# Crée l'artefact JAR exécutable

package:jar:
  stage: package
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "📦 Création du JAR exécutable..."
    - cd backend
    - mvn $MAVEN_CLI_OPTS package -DskipTests
    - echo "✅ JAR créé avec succès !"
    - ls -lh boot/target/*.jar
  artifacts:
    paths:
      - backend/boot/target/*.jar
    expire_in: 1 month
  only:
    - branches
    - tags
  tags:
    - docker

# ============================================
# STAGE 5 : DOCKER BUILD
# ============================================
# Construit l'image Docker et la pousse dans le registry

docker:build:
  stage: docker-build
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "🐳 Configuration Docker..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "🏗️ Construction de l'image Docker..."
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG -t $DOCKER_IMAGE_NAME:latest -f Dockerfile .
    - echo "📤 Push de l'image vers le registry..."
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_TAG
    - docker push $DOCKER_IMAGE_NAME:latest
    - echo "✅ Image Docker créée : $DOCKER_IMAGE_NAME:$DOCKER_TAG"
  dependencies:
    - package:jar
  only:
    - main
    - corentin/dev
    - tags
  tags:
    - docker

# ============================================
# STAGE 6 : DEPLOY
# ============================================
# Déploiement sur environnement de développement

deploy:dev:
  stage: deploy
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "🔧 Configuration du déploiement..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "🚀 Déploiement sur l'environnement de développement..."

    # Arrêt et suppression des conteneurs existants
    - docker stop bank-account-app || true
    - docker rm bank-account-app || true
    - docker stop bank-account-db || true
    - docker rm bank-account-db || true

    # Création du réseau Docker si nécessaire
    - docker network create bank-account-network || true

    # Démarrage de la base de données PostgreSQL
    - |
      docker run -d \
        --name bank-account-db \
        --network bank-account-network \
        -e POSTGRES_DB=bankaccount \
        -e POSTGRES_USER=bankuser \
        -e POSTGRES_PASSWORD=bankpass \
        -p 5432:5432 \
        postgres:15-alpine

    # Attente que la base de données soit prête
    - echo "⏳ Attente du démarrage de PostgreSQL..."
    - sleep 10

    # Démarrage de l'application
    - |
      docker run -d \
        --name bank-account-app \
        --network bank-account-network \
        -e SPRING_PROFILES_ACTIVE=dev \
        -e SPRING_DATASOURCE_URL=jdbc:postgresql://bank-account-db:5432/bankaccount \
        -e SPRING_DATASOURCE_USERNAME=bankuser \
        -e SPRING_DATASOURCE_PASSWORD=bankpass \
        -p 8080:8080 \
        $DOCKER_IMAGE_NAME:$DOCKER_TAG

    - echo "✅ Application déployée avec succès !"
    - echo "📍 URL de l'application : http://localhost:8080"
    - echo "📍 Swagger UI : http://localhost:8080/swagger-ui.html"

    # Affichage des logs
    - sleep 5
    - docker logs bank-account-app
  environment:
    name: development
    url: http://localhost:8080
  only:
    - corentin/dev
  when: manual  # Déploiement manuel pour l'environnement de dev
  tags:
    - docker

# Déploiement sur environnement de production
deploy:prod:
  stage: deploy
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "🔧 Configuration du déploiement production..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "🚀 Déploiement sur l'environnement de production..."

    # Arrêt et suppression des conteneurs existants
    - docker stop bank-account-app-prod || true
    - docker rm bank-account-app-prod || true
    - docker stop bank-account-db-prod || true
    - docker rm bank-account-db-prod || true

    # Création du réseau Docker si nécessaire
    - docker network create bank-account-network-prod || true

    # Démarrage de la base de données PostgreSQL
    - |
      docker run -d \
        --name bank-account-db-prod \
        --network bank-account-network-prod \
        -e POSTGRES_DB=bankaccount \
        -e POSTGRES_USER=bankuser \
        -e POSTGRES_PASSWORD=${DB_PASSWORD} \
        -v bank-account-db-data:/var/lib/postgresql/data \
        -p 5433:5432 \
        postgres:15-alpine

    # Attente que la base de données soit prête
    - echo "⏳ Attente du démarrage de PostgreSQL..."
    - sleep 10

    # Démarrage de l'application
    - |
      docker run -d \
        --name bank-account-app-prod \
        --network bank-account-network-prod \
        -e SPRING_PROFILES_ACTIVE=prod \
        -e SPRING_DATASOURCE_URL=jdbc:postgresql://bank-account-db-prod:5432/bankaccount \
        -e SPRING_DATASOURCE_USERNAME=bankuser \
        -e SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD} \
        --restart unless-stopped \
        -p 8081:8080 \
        $DOCKER_IMAGE_NAME:$DOCKER_TAG

    - echo "✅ Application déployée en production avec succès !"
    - echo "📍 URL de l'application : http://localhost:8081"

    # Affichage des logs
    - sleep 5
    - docker logs bank-account-app-prod
  environment:
    name: production
    url: http://localhost:8081
  only:
    - main
    - tags
  when: manual  # Déploiement manuel pour la production
  tags:
    - docker

# ============================================
# JOB DE NETTOYAGE (optionnel)
# ============================================
# Nettoie les anciennes images Docker

cleanup:docker:
  stage: deploy
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo "🧹 Nettoyage des anciennes images Docker..."
    - docker image prune -a -f --filter "until=168h"
    - echo "✅ Nettoyage terminé !"
  only:
    - schedules
  tags:
    - docker